### ISSUE TITLE
How to load ressource at runtime?

### ISSUE THREAD

**Issue by wiiznokes** [crabnebula-dev/cargo-packager#97]
Is there plan to make a loader ressource path or somethings? It would be usefull.

**Comment by denjell-crabnebula** [comment]
These are generally taken care of by the framework, I humbly recommend https://tauri.apps/

It has two methods that might be helpful.

https://tauri.app/v1/guides/building/sidecar
https://tauri.app/v1/guides/building/resources

**Comment by denjell-crabnebula** [comment]
Of course if I misunderstood your question, please feel free to reopen and clarify what you need. :)

**Comment by wiiznokes** [comment]
I would be happy to make a PR for that. I'm thinking it just a crate that search `CARGO_PACKAGER_FORMAT` env variable, and provide a impl for each formats.

What would be the name of this crate tho ?

> a more fleshed out feature request 
You mean in this issue, or there is another process i'm not aware of ?

**Comment by amr-crabnebula** [comment]
Unfortunately since cargo-packager is just a tool to create the package we can't add a resource resolver in it, this has to be done in one of two ways:
- a separate crate e.g. `cargo-packager-resource-resolver`
- outline and document how the resources are copied over in the final bundle and maybe provide and example of a resource resolver implementation that can be copy/pasted.
